version: '3'

networks:
    default:
        driver: bridge
        ipam:
            config:
                - subnet: 172.177.57.0/24

services:
    redis:
        image: redis
        ports:
            - '6379:6379'
        volumes:
            - /path/to/nginx.conf:/etc/nginx/conf.d/default.conf:ro

    bot:
        build: .
        volumes:
            - ./:/app
        stdin_open: true
        tty: true
